### ISSUE TITLE
Problems running expokit_dgpadm_Qmat() in parallel

### ISSUE THREAD

**Issue by joelnitta** [nmatzke/rexpokit#3]
Hello!

This is actually related to [BioGeoBEARS](https://github.com/nmatzke/BioGeoBEARS), but I tracked my problem down to the `expokit_dgpadm_Qmat()` function in this package.

I need to run `BioGeoBEARS::bears_optim_run()` in parallel because I have a very large dataset (9 regions, ca. 7,000 tips). I am trying to get it to work on a smaller dataset (80 tips) first before I scale up to the full one.

I noticed during my attempts to run in parallel that even though I only specified a limited number of cores with `num_cores_to_use` in the settings list, when I monitored the run, it seemed like all of the available cores were getting used. I eventually tracked this down to the behavior of `expokit_dgpadm_Qmat()`. 

I am having the following problems:
- Even when running in serial, `expokit_dgpadm_Qmat()` causes all cores available to fire. 
- When I run `expokit_dgpadm_Qmat()` in parallel, using either `clusterApply()` as in BioGeoBEARS or `furrr::future_map()`, the run time hardly improves

At the end I pasted a reprex to show that the run time does not improve when running in parallel.

Here are some examples of what memory usage looks like on my lab server using `htop` when I run `expokit_dgpadm_Qmat()` using the data in the reprex:

Background (none of my jobs are running):

![rexpokit_not-running](https://user-images.githubusercontent.com/13459362/109361510-63535800-78cc-11eb-93c2-2552a6c8898d.jpg)

`expokit_dgpadm_Qmat()` running in serial (notice all the cores are running, but not to 100%):

![rexpokit_serial](https://user-images.githubusercontent.com/13459362/109361579-8aaa2500-78cc-11eb-8f3e-41659a68b9fc.jpg)

`expokit_dgpadm_Qmat()` running in parallel with `clusterApply()` and `makeCluster(getOption("cl.cores", 4))` (notice all the cores are 100%, and load average goes way up from here):

![rexpokit_parallel](https://user-images.githubusercontent.com/13459362/109361661-b9c09680-78cc-11eb-97b9-3050b092c899.jpg)

Below is the reprex showing that running in parallel doesn't speed things up significantly.

``` r
library(rexpokit)
library(parallel)
library(tictoc)
library(purrr)
library(future)
library(furrr)
library(peakRAM)
library(tictoc)
library(ape)

# Load test data

# The Qmat and phy2 were extracted from debugging BioGeoBEARS::bears_optim_run() by
# calling debugonce(mapply_likelihoods) before running bears_optim_run()
temp_file <- paste0(tempfile(), ".RDS")
download.file("https://www.dropbox.com/s/y5m9o9y66bxvd6y/Qmat.RDS?dl=1", temp_file)
Qmat <- readRDS(temp_file)

dim(Qmat)
#> [1] 382 382

temp_file <- paste0(tempfile(), ".RDS")
download.file("https://www.dropbox.com/s/3bljjfuzdru37r7/phy2.RDS?dl=1", temp_file)
phy2 <- readRDS(temp_file)

phy2
#> 
#> Phylogenetic tree with 80 tips and 79 internal nodes.
#> 
#> Tip labels:
#>  Elaphoglossum_amygdalifolium, Elaphoglossum_andicola, Elaphoglossum_lepervanchii, Elaphoglossum_luridum, Elaphoglossum_metallicum, Elaphoglossum_delgadilloanum, ...
#> Node labels:
#>  100, 100, 100, 100, 80, 97, ...
#> 
#> Rooted; includes branch lengths.

# Check memory usage and time of running on just one edge
tic()
mem <- peakRAM({
  test <- rexpokit::expokit_dgpadm_Qmat(
    Qmat = Qmat, t = phy2$edge.length[1], transpose_needed = TRUE)
})
toc()
#> 0.238 sec elapsed
mem$Peak_RAM_Used_MiB
#> [1] 13.5

# Check memory usage and time of looping across edges
# increase the number of edges by 8 for better comparison with running in parallel
tic()
mem <- peakRAM::peakRAM({
  independent_likelihoods_on_each_branch_list <- map2(
    list(Qmat), 
    rep(phy2$edge.length, 8),
    ~rexpokit::expokit_dgpadm_Qmat(Qmat = .x,  t = .y, transpose_needed = TRUE)
  )
})
toc()
#> 142.643 sec elapsed
mem$Peak_RAM_Used_MiB
#> [1] 1850.8

# Try running in parallel with clusterApply in the parallel package
# Verify that clusterApply is working as expected (this should require about 2 
# seconds if processes are running in parallel)
cluster_already_open <- makeCluster(getOption("cl.cores", 4))

tic()
clusterApply(cl = cluster_already_open, x = c(2, 2, 2, 2), fun = function (x) Sys.sleep(x))
#> [[1]]
#> NULL
#> 
#> [[2]]
#> NULL
#> 
#> [[3]]
#> NULL
#> 
#> [[4]]
#> NULL
toc()
#> 2.008 sec elapsed

# Check memory usage and time of looping across edges in parallel (clusterApply)
tictoc::tic()
mem <- peakRAM::peakRAM({
  independent_likelihoods_on_each_branch <- clusterApply(
    cl = cluster_already_open, 
    fun = rexpokit::expokit_dgpadm_Qmat, 
    x = rep(phy2$edge.length, 8),
    Qmat = Qmat, 
    transpose_needed = TRUE)
})
tictoc::toc()
#> 128.456 sec elapsed
mem$Peak_RAM_Used_MiB
#> [1] 1409.7

stopCluster(cluster_already_open)

# Try running in parallel with future_map2 in the furrrr package
# Before running in parallel, set parallel backend.
# here, we are using 4 processes in parallel
future::plan(multisession, workers = 4)

# Verify that future_map is working as expected (this should require about 2 
# seconds if processes are running in parallel)
tic()
nothingness <- future_map(c(2, 2, 2, 2), ~Sys.sleep(.x))
toc()
#> 2.337 sec elapsed

# Check memory usage and time of looping across edges in parallel (future_map2)
tictoc::tic()
mem <- peakRAM::peakRAM({
  independent_likelihoods_on_each_branch_list <- future_map2(
    list(Qmat), 
    rep(phy2$edge.length, 8),
    ~rexpokit::expokit_dgpadm_Qmat(Qmat = .x,  t = .y, transpose_needed = TRUE)
  )
})
tictoc::toc()
#> 120.714 sec elapsed
mem$Peak_RAM_Used_MiB
#> [1] 1408.1
```

<sup>Created on 2021-02-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> Error in get(genname, envir = envir) : object 'testthat_print' not found
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 4.0.0 (2020-04-24)
#>  os       Ubuntu 20.04 LTS            
#>  system   x86_64, linux-gnu           
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    en_US.UTF-8                 
#>  tz       Etc/UTC                     
#>  date     2021-02-26                  
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  ! package     * version  date       lib source                           
#>    ape         * 5.3      2019-03-17 [1] CRAN (R 4.0.0)                   
#>    assertthat    0.2.1    2019-03-21 [1] CRAN (R 4.0.0)                   
#>    backports     1.1.5    2019-10-02 [1] CRAN (R 4.0.0)                   
#>    callr         3.5.1    2020-10-13 [1] CRAN (R 4.0.0)                   
#>    cli           2.0.2    2020-02-28 [1] CRAN (R 4.0.0)                   
#>  P codetools     0.2-16   2018-12-24 [?] CRAN (R 4.0.0)                   
#>    crayon        1.3.4    2017-09-16 [1] CRAN (R 4.0.0)                   
#>    desc          1.2.0    2018-05-01 [1] CRAN (R 4.0.0)                   
#>    devtools      2.2.2    2020-02-17 [1] CRAN (R 4.0.0)                   
#>    digest        0.6.25   2020-02-23 [1] CRAN (R 4.0.0)                   
#>    ellipsis      0.3.0    2019-09-20 [1] CRAN (R 4.0.0)                   
#>    evaluate      0.14     2019-05-28 [1] CRAN (R 4.0.0)                   
#>    fansi         0.4.1    2020-01-08 [1] CRAN (R 4.0.0)                   
#>    fs            1.5.0    2020-07-31 [1] CRAN (R 4.0.0)                   
#>    furrr       * 0.2.2    2021-01-29 [1] CRAN (R 4.0.0)                   
#>    future      * 1.21.0   2020-12-10 [1] CRAN (R 4.0.0)                   
#>    globals       0.14.0   2020-11-22 [1] CRAN (R 4.0.0)                   
#>    glue          1.3.1    2019-03-12 [1] CRAN (R 4.0.0)                   
#>    highr         0.8      2019-03-20 [1] CRAN (R 4.0.0)                   
#>    htmltools     0.4.0    2019-10-04 [1] CRAN (R 4.0.0)                   
#>    knitr         1.28     2020-02-06 [1] CRAN (R 4.0.0)                   
#>    lattice       0.20-38  2018-11-04 [1] CRAN (R 4.0.0)                   
#>    listenv       0.8.0    2019-12-05 [1] CRAN (R 4.0.0)                   
#>    magrittr      1.5      2014-11-22 [1] CRAN (R 4.0.0)                   
#>    memoise       1.1.0    2017-04-21 [1] CRAN (R 4.0.0)                   
#>    nlme          3.1-142  2019-11-07 [1] CRAN (R 4.0.0)                   
#>    parallelly    1.23.0   2021-01-04 [1] CRAN (R 4.0.0)                   
#>    peakRAM     * 1.0.2    2017-01-16 [1] CRAN (R 4.0.0)                   
#>    pkgbuild      1.0.6    2019-10-09 [1] CRAN (R 4.0.0)                   
#>    pkgload       1.0.2    2018-10-29 [1] CRAN (R 4.0.0)                   
#>    prettyunits   1.1.1    2020-01-24 [1] CRAN (R 4.0.0)                   
#>    processx      3.4.5    2020-11-30 [1] CRAN (R 4.0.0)                   
#>    ps            1.3.2    2020-02-13 [1] CRAN (R 4.0.0)                   
#>    purrr       * 0.3.3    2019-10-18 [1] CRAN (R 4.0.0)                   
#>    R6            2.4.1    2019-11-12 [1] CRAN (R 4.0.0)                   
#>    Rcpp          1.0.3    2019-11-08 [1] CRAN (R 4.0.0)                   
#>    remotes       2.1.1    2020-02-15 [1] CRAN (R 4.0.0)                   
#>    renv          0.12.5   2021-01-09 [1] CRAN (R 4.0.0)                   
#>    rexpokit    * 0.26.6.7 2021-02-17 [1] Github (nmatzke/rexpokit@2e7712f)
#>    rlang         0.4.10   2020-12-30 [1] CRAN (R 4.0.0)                   
#>    rmarkdown     2.1      2020-01-20 [1] CRAN (R 4.0.0)                   
#>    rprojroot     1.3-2    2018-01-03 [1] CRAN (R 4.0.0)                   
#>    sessioninfo   1.1.1    2018-11-05 [1] CRAN (R 4.0.0)                   
#>    stringi       1.4.6    2020-02-17 [1] CRAN (R 4.0.0)                   
#>    stringr       1.4.0    2019-02-10 [1] CRAN (R 4.0.0)                   
#>    testthat      2.3.2    2020-03-02 [1] CRAN (R 4.0.0)                   
#>    tictoc      * 1.0      2014-06-17 [1] CRAN (R 4.0.0)                   
#>    usethis       1.5.1    2019-07-04 [1] CRAN (R 4.0.0)                   
#>    vctrs         0.3.6    2020-12-17 [1] CRAN (R 4.0.0)                   
#>    withr         2.1.2    2018-03-15 [1] CRAN (R 4.0.0)                   
#>    xfun          0.12     2020-01-13 [1] CRAN (R 4.0.0)                   
#>    yaml          2.2.1    2020-02-01 [1] CRAN (R 4.0.0)                   
#> 
#> [1] /renv/R-4.0/x86_64-pc-linux-gnu
#> [2] /tmp/RtmpTgpClN/renv-system-library
#> [3] /tmp/RtmpAYks8L/renv-system-library
#> 
#>  P ── Loaded and on-disk path mismatch.
```

</details>

**Comment by nmatzke** [comment]
Hi- what’s your operating system? As far as I know this is more likely to
be an issue with how clusterApply etc work/dont wirj in your system, than a
rexpokit issue...

**Comment by joelnitta** [comment]
Thanks for the quick response!

The screenshots are from running this on linux:
```
(base) [joelnitta@juno bgb_test]$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

I agree that the OS likely has something to do with it, as I don't see the same behavior in terms of use of cores when I run it on my Mac (they don't all go to 100%). Actually, the reprex is from running it on my Mac - I didn't want to suck up all of the cores on the lab server just to make the reprex. But as you can see from the reprex, there is very little speed gained from running in parallel, which made me think it might have something to do with `expokit_dgpadm_Qmat()` itself.

Here is the info for my mac:

```
(base) Joels-iMac:~ joelnitta$ sw_vers         
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H524
```

**Comment by wrathematics** [comment]
Just a guess, but are you using multi-threaded BLAS on the cluster but not your laptop? Because that would do it. You can see what BLAS/LAPACK library you're using in modern R versions using `sessionInfo()` (but it wasn't included in your devtools call).

You could try testing with something like:

```
OMP_NUM_THREADS=1 Rscript my_script.r
```

**Comment by nmatzke** [comment]
Thanks Drew!  I don't know how this interacts with other BLAS/LAPACK but
rexpokit contains a few .f files derived from the original EXPOKIT, these
include a blas and lapack that probably date way back.

**Comment by joelnitta** [comment]
Thank you so much @wrathematics! This completely solved it. Core usage looks fine, and now there is a considerable speed up gained by running in parallel, at least twice as fast.

@nmatzke I don't know if there are any changes that need to be made here, but you might consider adding some documentation to BioGeoBEARS about this issue.

Thanks again to both of you!

**Comment by wrathematics** [comment]
For OpenBLAS, you can set `OPENBLAS_NUM_THREADS` and still get other OMP parallelism (but it sounds like you may not want to).

To set the number of OMP threads dynamically from R, you can use the [OpenMPController package](https://cran.r-project.org/web/packages/OpenMPController/index.html) or the [omp package](https://github.com/wrathematics/omp). However this won't work with OpenBLAS (sort of explained [here](https://github.com/wrathematics/openblasctl/blob/master/R/openblas_set_num_threads.r#L6-L13)).

To set the number of OpenBLAS threads dynamically from R, you can use the [openblasctl package](https://github.com/wrathematics/openblasctl).

**Comment by joelnitta** [comment]
Thanks for the additional info!

It sounds like there are two layers of parallelization involved when running `expokit_dgpadm_Qmat()` in the context of BioGeoBEARS:
- `expokit_dgpadm_Qmat()` has code that can run in parallel (and in my case, does so automatically unless over-ridden by setting `OMP_NUM_THREADS`).
- Within BioGeoBEARS, `expokit_dgpadm_Qmat()` is run in parallel over each branch in the phylogeny by setting `num_cores_to_use` > 1.

I'm guessing I will get the best performance by setting `OMP_NUM_THREADS` to 1, and running `expokit_dgpadm_Qmat()` in parallel with `num_cores_to_use`, but it is possible some other arrangement might be better (e.g., `OMP_NUM_THREADS` to 2, etc). Any thoughts about that? (besides just experimenting).

**Comment by nmatzke** [comment]
Hi!  My suspicion is that the parallelization is only useful once the
matrix exponentiations get big and slow, e.g. when the number of geographic
states gets well above 100 (i.e. 7+ areas), especially above 500 or so.
Each exponentiation takes a chunk of second, so you might as well farm out
all the branches to separate cores.  Below that, the exponentiations are
fast enough that the overhead inside of R slows it down compared to the
very fast matrix exponentiations. But people could experiment if they
like!  I am currently working more in ODE-world and trying to speed that
stuff up for large problems, so I'm not doing much beyond maintenance with
BioGeoBEARS -- cheers and thanks for tracking this down!

Cheers,
Nick

**Comment by joelnitta** [comment]
That makes sense, thanks Nick!
As far as I'm concerned this is resolved, so I'll close the issue. But feel free to reopen if you think there's something else that needs more attention.
